  rathole:
    image: rapiz1/rathole:v0.5.0
    container_name: rathole
    command: --client /config/rathole.client.toml
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/client.toml:/config/rathole.client.toml:ro
    networks:
      - proxy