services:
  proxy-tunnel:
    build: .
    container_name: proxy-tunnel
    networks:
      - dokploy-network
    environment:
      VPS_TUNNEL_PORT: 3001   # The remote SSH tunnel port
      DOMAIN_NAME: homelab.beznet.org
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-tunnel.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.socat.entrypoints=websecure"
      - "traefik.http.routers.socat.tls.certResolver=letsencrypt"
      - "traefik.http.services.socat.loadbalancer.server.port=3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dokploy-network:
    external: true
