version: "3.8"
services:
  frpc:
    image: snowdreamtech/frpc:alpine
    container_name: frpc
    restart: always
    volumes:
      - ./frp/frpc.toml:/etc/frp/frpc.toml:ro
    command: ["-c", "/etc/frp/frpc.toml"]
    ports:
      - "7400:7400"
