services:
  proxy-tunnel:
    build: .
    networks:
      - dokploy-network
    environment:
      VPS_TUNNEL_PORT: 3001   # The SSH reverse tunnel port on VPS
      DOMAIN_NAME: homelab.beznet.org
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-tunnel.rule=Host(`homelab.beznet.org`)"
      - "traefik.http.routers.socat.entrypoints=websecure"
      - "traefik.http.routers.socat.tls.certResolver=letsencrypt"
      - "traefik.http.services.socat.loadbalancer.server.port=80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dokploy-network:
    external: true
