version: "3.8"

services:
  proxy-tunnel:
    image: alpine/socat
    command: -v tcp-listen:80,fork,reuseaddr tcp-connect:host.docker.internal:${HOST_SSH_PORT}
    networks:
      - dokploy-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.node-tunnel.rule=HostSNI(`${DOMAIN_NAME}`)"
      - "traefik.tcp.routers.node-tunnel.entrypoints=websecure"
      - "traefik.tcp.routers.node-tunnel.tls=true"
      - "traefik.tcp.services.node-tunnel.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
