services:
  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Lagos
      - PASSWORD_ACCESS=yes
      - PUBLIC_KEY=${PUBLIC_KEY}
      - USER_NAME=localtunnel
      - SUDO_ACCESS=no
    ports:
      - "2222:2222"   # optional for external access
    networks:
      - dokploy-network

  proxy-tunnel:
    build: .
    networks:
      - dokploy-network
    environment:
      VPS_TUNNEL_PORT: 3001   # The SSH reverse tunnel port on VPS
      DOMAIN_NAME: homelab.beznet.org
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-tunnel.rule=Host(`homelab.beznet.org`)"
      - "traefik.http.routers.socat.entrypoints=websecure"
      - "traefik.http.routers.socat.tls.certResolver=letsencrypt"
      - "traefik.http.services.socat.loadbalancer.server.port=80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dokploy-network:
    external: true
