[client]
remote_addr = "37.60.235.96:2333"

[client.transport]
type = "noise"

[client.transport.noise]
remote_public_key = "7y0rlQKYvEDdjM4xZ26G2Tk6CS8Dx+G1ZIu5M3vlxjc="

# single client per tunnels pair

# portal
[client.services.portal]
token = "secret_token_1"
local_addr = "127.0.0.1:555"