[server]
bind_addr = "0.0.0.0:2333"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "${PRIVATE_KEY}"

[server.services.portal]
token = "secret_token_1"
bind_addr = "0.0.0.0:5555"
