server_addr = "37.60.235.96"   # replace with public IP or domain
server_port = 7000

[auth]
token = "myVeryStrongToken123"

[[proxies]]
name = "ssh_homelab"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6000

[[proxies]]
name = "web_homelab"
type = "http"
local_ip = "127.0.0.1"
local_port = 80
custom_domains = ["lab.beznet.org"] # use your own domain with DNS A record pointing to your FRPS server IP