[common]
# Address of the FRPS server
server_addr = "37.60.235.96"
server_port = 7000

# Authentication must match frps.toml
# auth.method = "token"
# auth.token = "your_secret_token"

# Optional: enable client web UI (useful for debugging)
# webServer.addr = "0.0.0.0"
# webServer.port = 7400
# webServer.user = "admin"
# webServer.password = "admin123"

# Transport tuning (optional)
# transport.poolCount = 1
# transport.tcpMux = true
# transport.protocol = "tcp"  # or "kcp" or "quic" if configured on server
# transport.connectServerLocalIP = ""

# Example 1: Expose local SSH server on remote port 6000
[[proxies]]
name = "ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6000

# Example 2: Expose a local web server via HTTP domain
[[proxies]]
name = "web"
type = "http"
local_ip = "127.0.0.1"
local_port = 3000
custom_domains = ["homelab.beznet.org"]

# Example 3 (Optional): HTTPS proxy
# [[proxies]]
# name = "web-https"
# type = "https"
# local_ip = "127.0.0.1"
# local_port = 443
# custom_domains = ["www.example.com"]
