serverAddr = "37.60.235.96"
serverPort = 7000

auth.method = "token"
auth.token = "super_secret_token"

[[proxies]]
name = "homelab_ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "homelab_http"
type = "http"
localIP = "127.0.0.1"
localPort = 80
custom_domains = ["lab.beznet.org"] # use your own domain with DNS A record pointing to your FRPS server IP
