serverAddr = "37.60.235.96"

[auth]
token = "myVeryStrongToken123"

[[proxies]]
name = "ssh_homelab"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "web_homelab"
type = "http"
localIP = "127.0.0.1"
localPort = 80
customDomains = ["lab.beznet.org"]
