[common]
bind_port = 7000

# Dashboard / web UI (if enabled)
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin123"

# HTTP / HTTPS vhost ports
vhostHTTPPort = 8080
vhostHTTPSPort = 8443

auth.method = "token"
auth.token = "your_secret_token"
