bindAddr = "0.0.0.0"
bindPort = 7000

# HTTP / HTTPS vhost ports (for http / https type proxies)
vhostHTTPPort = 8080
vhostHTTPSPort = 8443

# Dashboard / web UI configuration
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

# Authentication (must match client)
auth.method = "token"
auth.token = "your_secret_token"

# (Optional) Transport tuning — minimal defaults are OK
transport.maxPoolCount = 5

