bindAddr = "0.0.0.0"
bindPort = 7000

# HTTP proxy
vhostHTTPPort = 8080

# Dashboard
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

# Authentication
auth.method = "token"
auth.token = "super_secret_token"
